version: "2.1"
services:
  jellyfin:
    build: ./config/jellyfin
    container_name: jellyfin
    group_add:
      - video
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - JELLYFIN_PublishedServerUrl=${DOCKER_GATEWAY_HOST:-host.docker.internal}
    volumes:
      - ./config/jellyfin:/config
      - ./library/tvshows:/data/tvshows
      - ./library/movies:/data/movies
    ports:
      - "8096:8096"
    devices:
      - /dev/video0
      - /dev/video1
      - /dev/video2
      - /dev/video3
      - /dev/video4
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn:master
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=false
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=$TRANSMISSION_RPC_USERNAME
      - TRANSMISSION_RPC_PASSWORD=$TRANSMISSION_RPC_PASSWORD
      - TRANSMISSION_PORT_FORWARDING_ENABLED=true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/transmission:/config
      - ./downloads:/data
    expose:
      - 9091
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config/radarr:/config
      - ./library/movies:/movies
      - ./downloads:/data
    expose:
      - 7878
    restart: unless-stopped

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ./downloads:/downloads
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Europe/Stockholm
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}

  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config/sonarr:/config
      - ./library/tvshows:/tv
      - ./downloads:/data
    expose:
      - 8989
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:development
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config/bazarr:/config
      - ./library/movies:/movies
      - ./library/tvshows:/tv
    expose:
      - 6767
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 21600
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./config/nginx
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./config/certbot/www:/var/www/certbot/:ro
      - ./config/certbot/conf:/etc/letsencrypt:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    depends_on:
      - jellyfin
      - radarr
      - sonarr
      - bazarr
      - transmission
      - prowlarr

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt:rw
      - ./config/certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config/prowlarr:/config
    expose:
      - 9696
    restart: unless-stopped

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Stockholm
    expose:
      - 8191
    restart: unless-stopped

  cross-seed:
    image: crossseed/cross-seed
    container_name: cross-seed
    user: 1000:1000
    volumes:
      - ./config/cross-seed:/config
      - ./downloads/transmission-home/torrents:/torrents:ro
      - ./downloads/completed/:/cross-seeds:ro
    command: search

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    environment:
      - API_KEY=${CLOUDFLARE_TOKEN}
      - ZONE=trewhitt.se
      - SUBDOMAIN=jelly
      - PROXIED=false
